{% set name = "clifford" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pygae/{{ name }}/archive/v{{ version }}.zip
  sha256: e7d2287a77e39d015fe4435d69ba2b8c53797cd2632462400e927abcee899cef

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip   
  run:
    - python
    - numpy
    - scipy
    - numba
    - future
    - h5py
    


test:
  imports:
    - clifford

about:
  home: http://clifford.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'A numerical geometric algebra module for python. BSD License.'

  description: |
    This module implements Geometric Algebras (a.k.a. Clifford algebras). Geometric Algebra (GA) is a universal algebra which subsumes complex algebra, quaternions, linear algebra and several other independent mathematical systems. Scalars, vectors, and higher-grade entities can be mixed freely and consistently in the form of mixed-grade multivectors.
  doc_url: http://clifford.readthedocs.io
  dev_url: https://github.com/pygae/clifford

extra:
  recipe-maintainers:
    - arsenovic
    - hugohadfield
    - eric-wieser
