{% set name = "clifford" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pygae/{{ name }}/archive/v{{ version }}.zip
  sha256: fa02bac727757be464143aebd75c274e9dc388a574d77cf03342eacc3cfa5b23

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - numpy
    - scipy
    - numba >0.46,!=0.49.0rc1,<0.50.0
    - sparse
    - h5py



test:
  imports:
    - clifford

about:
  home: http://clifford.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A numerical geometric algebra module for python. BSD License.

  description: |
    This module implements Geometric Algebras (a.k.a. Clifford algebras). Geometric Algebra (GA) is a universal algebra which subsumes complex algebra, quaternions, linear algebra and several other independent mathematical systems. Scalars, vectors, and higher-grade entities can be mixed freely and consistently in the form of mixed-grade multivectors.
  doc_url: http://clifford.readthedocs.io
  dev_url: https://github.com/pygae/clifford

extra:
  recipe-maintainers:
    - arsenovic
    - hugohadfield
    - eric-wieser
