travis:
  secure:
    BINSTAR_TOKEN: R8+3J2ROTCN9JHoi63VGVfW0k35ZOFbN0LlmzUIXcgrsOe4Qpfzj04ojqeFUGp/MPG3luRuGuxbWfpwHVBOrgDtEnmqc1fvLsOmF9Kxs7Nvz4zUFt4aAB50UlCGM86rY9e0/EkJE1eZiTRDiMrGNeHlJNeq3z5tRk+S3D/J+8m+dlEcHENSYhgc2A7Ck4E8rz7bCqpwY3qsefXznnV/JKX471kGTCG7z2AnFcynEfgRRQwhBxmKRbJ2RJQvgSSytdCKJUyfcu4jjJXow2GMWclm+n2j6Qsq4HV+7OMhZLITJ8PAp/jJPfzBbKll0CQyE9JnAOTOJUF0XXHOt7pdYT+EAvPLHxKf/yGXUi+9SheAU/jckRHxJwHrq+ZVJ+XhKSOk3E9NJukLAIgMBX3sdre79Z811TpMK4ouKiXrcr0QS+WVUOQyAtCBHhRbXYrK05clx4FP+t6O2569LQ6ASE8H5YIIOFTLfdQ56P/HLcI2wkjbHi+V/wAAW44wVvcuzJXcCiViMYq6+fElMznuDSBDICTvBDHyULz04MlVgYzQL3iFT9BUuqMvFCFteFS5SF8p3wap4tzSYglMGpOXNLPGdUfxDkmCKjiVeYuJKOqIk2r0Q5cvdxlghFNxhtkR1ewT+S3fGozGdkjyt2MuxxF51XWU3AQe++ZfDdni7BNQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
